define({
    'upDnAccEinstant_win': {
        "fill": ["#fefeea", "#fdf944", "#f9d040", "#fff17d"],
        "fillGradientStops": [0.2, 0.6, 0.6, 0.8],
        "dropShadowAlpha": 0.8,
        "dropShadowAngle": 3.4,
        "dropShadowBlur": 9,
        "dropShadowColor": "#ffffdf",
        "dropShadowDistance": 0,
        "lineJoin": "round",
        "miterLimit": 11,
        "stroke": "#eb1d1d",
        "strokeThickness": 4
    },
    'upDnAccEinstant_nowin': {
        "fill": ['#ffffff', "#f2e894", "#bad4ff", '#ffffff'],
        "fillGradientStops": [0.3, 0.5, 0.5, 0.7],
        "dropShadow": true,
        "dropShadowAngle": 14.4,
        "dropShadowBlur": -8,
        "dropShadowColor": "#117ba7",
        "dropShadowDistance": 2,
        "lineJoin": "round",
        "miterLimit": 13,
    },
    'eInstantWin_win': {
        "fill": ["#fffcda", "#fff830", "#ffa405", "#f7e533"],
        "fillGradientStops": [0.3, 0.62, 0.65, 0.78],
        "dropShadow": true,
        "dropShadowAngle": -3.7,
        "dropShadowBlur": 8,
        "dropShadowColor": "#fdffea",
        "dropShadowDistance": 0,
        "fontSize": 60,
        "lineJoin": "round",
        "miterLimit": 11,
        "stroke": "#b71207",
        "strokeThickness": 5
    },
    'eInstantWin_nowin': {
        "dropShadow": true,
        "dropShadowAlpha": 0.9,
        "dropShadowAngle": -0.3,
        "dropShadowBlur": -12,
        "dropShadowColor": "#d55c0b",
        "dropShadowDistance": -2,
        "fontSize": 42,
        "lineJoin": "round",
        "miterLimit": 11,
        "stroke": "#eb1d1d",
        "strokeThickness": 4
    },
    'eInstantWin_nowin_80': {
        "dropShadow": true,
        "dropShadowAngle": -3.7,
        "dropShadowBlur": 8,
        "dropShadowColor": "#fdffea",
        "dropShadowDistance": 0,
        "fontSize": 42,
        "lineJoin": "round",
        "miterLimit": 11,
        "stroke": "#b71207",
        "strokeThickness": 5
    },
    'spinLeft': {
        dropShadow: true,
        dropShadowDistance: 8,
    },
    'pickBonusTips': {
        dropShadow: true,
        dropShadowBlur: 10,
        dropShadowColor: '#7f398d',
        dropShadowDistance: 0,
    },
    'buttonStyle': {},
    'tutorialTextStyle': {
        "dropShadowAlpha": 0.8,
        "dropShadowAngle": 3.4,
        "dropShadowBlur": 9,
        "dropShadowColor": "#ffffdf",
        "dropShadowDistance": 0,
        fontSize: 32,
        lineJoin: "round",
        miterLimit: 28,
        padding: 41,
    },
    "climberTotalText": {
        dropShadow: true,
        dropShadowDistance: 2,
        dropShadowAlpha: 0.7,
        dropShadowBlur: 6,
        dropShadowColor: "#000000"
    },
});